# beginning of file Makefile.conf


## ACGM: all configurations that were in "Makefile"
## in the old version of xmorph are now in this file,
## and here we discuss what has been changed


## DEFINES: C precompiler macros
## -----------------------------
#
# GIMP: Adds GIMP plugin functionality to xmorph.
#   Also define NEED_GIMP=1.  If this is defined, then you may run
#   xmorph both as a standalone application, and by adding it to your
#   ~/.gimp/plug-ins directory (usually via a symlink).  From what I
#   understand, this will not work for tkmorph.  See GIMPLIBS, below.
#
# REAL: Size of a "REAL" used by spline code.
#   Correct value is "double".  Do not change.
#
# RGBA_MESH_WARP: flag to tell RgbaImage to include mesh-based warping
#   methods.  Do not change.
#
# RGBA_TK: flag to tell RgbaImage to include Tk Photo image code.
#   DO NOT DEFINE for xmorph.  Only define for tkmorph.
#   Also change the "all" target if RGBA_TK is changed.
#
# RED_GREEN_COLOR_BLIND: uses blue instead of red for color of
#   'destination' mesh lines and points.
#
# STRDUP_PROTO_BROKEN: For some versions of GNU C, the string.h
#   header file has an incorrect prototype for strdup.  If you
#   experience problems compiling, related to the strdup prototype,
#   then define STRDUP_PROTO_BROKEN.


# For tkmorph:
#DEFINES=-DREAL=double -DRGBA_MESH_WARP -DRGBA_TK

# For colorblind:
#DEFINES=-DREAL=double -DRGBA_MESH_WARP -DRED_GREEN_COLOR_BLIND

# For GIMP plugin:
#DEFINES=-DREAL=double -DRGBA_MESH_WARP -DGIMP -DNEED_GIMP=1

# Broken GNU C:
#DEFINES=-DREAL=double -DRGBA_MESH_WARP -DSTRDUP_PROTO_BROKEN

# Most systems:
#DEFINES=-DREAL=double -DRGBA_MESH_WARP



## acgm: all program specific defines are done in  PROG/Makefile.am
## these are the generic defines
CFLAGS_CONF =  -DREAL=double -DRGBA_MESH_WARP




## XLIBS: X libraries
## ------------------
#
# Must have the X libraries: X11, MIT Athena Widgets, X Toolkit, X Misc Utils
#
# Linux 2.0: must have /usr/X11/lib
#   or /usr/X11R6/lib explicitly in library search path
#
# SunOS (pre-Solaris): Might have to use static X libraries because
#   dynamic X libraries are incomplete.
#
# Solaris: To link to openwin libraries, add -L/usr/openwin/lib
#
# IRIX6.2: Need to have -lcvt after -lXt
#   If you receive an error about an unresolved symbol named
#   SgCvtCreateConversionContext, you need to include -lcvt.
#   The cvt library is available in the goldengate.sw.goldengate package

# Sun Solaris:
#XLIBS=-L/usr/openwin/lib -lXaw -lXmu -lXext -lXt -lX11

# Linux:
#XLIBS=-L/usr/X11/lib -lXaw -lXmu -lXext -lXt -lX11
#XLIBS=-L/usr/X11R6/lib -lXaw -lXmu -lXext -lXt -lX11

# SGI IRIX:
#XLIBS=              -lXaw -lXmu -lXext -lXt -lcvt -lX11

## ACGM: this is the new autoconf way:
## unfortunately I would say that     -lcvt will not be added by default
##  for Irix systems....
##
XLIBS= @X_LIBS@ @X_PRE_LIBS@ -lXaw -lXmu -lXext -lXt -lX11 @X_EXTRA_LIBS@


## GIMPLIBS: GIMP libraries
## ------------------------
# If you have defined -DGIMP in the DEFINES section, then xmorph will
# be built to run both as a standalone application and as a GIMP
# plugin.  Here, you need to specify the appropriate GIMP libraries.
#
# Comment out this variable if you have not used -DGIMP.

#GIMPLIBS=-L/usr/local/lib -lgimp -lglib
#GIMPLIBS=-lgimp -lglib

## ACGM : if you do not use the GIMP, you still need to define the 
##  variable, otherwise Automake will warn you
GIMPLIBS=


## NON_GUI_LIBS: libraries which are not part of the GUI
## -----------------------------------------------------
#
# Must have the math library (-lm).
#
#
# Linux: Add -ldl if you get link error regarding dlerror, dlopen, or
#   dlsym
#
#
# FreeBSD: Do not use static libraries, because for some reason they
#   do not work.
#
#
# SunOS: Use the /usr/lib/debug/malloc.o module if you want to do
#   memory checking.
#   Also see the CFLAGS comments about memory checking under SunOS.
#
#
# SGI IRIX: Use -lmalloc to link with their special memory allocation
#   routines.  If you get an error about mallopt being
#   unresolved, then you will have to link with the libmalloc
#   shared object.  Do this by specifying -lmalloc here.
#
#   -lmalloc_cv has more robust memory checking

#NON_GUI_LIBS = -lm
#NON_GUI_LIBS = -lm -ldl
#NON_GUI_LIBS = -lm /usr/lib/debug/malloc.o
#NON_GUI_LIBS = -lm -lmalloc


## ACGM: we surely need this
NON_GUI_LIBS = -lm


## LIBS: loader options to link with libraries
## -------------------------------------------
#
### ACGM : the project now ignores this variable
#
# Read the man page for your linker before sending me email about
# problems.
#
# Apollo w/ Domain/OS, BSD: omit XLIBS

#LIBS = $(GIMPLIBS) $(NON_GUI_LIBS)
#LIBS =





# end of file Makefile.conf