/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_main (void);
GtkWidget* create_imageselection1 (void);
GtkWidget* create_image_win_1 (void);
GtkWidget* create_dialogwarning (void);
GtkWidget* create_window_warped (void);
GtkWidget* create_menuEditMesh (void);
GtkWidget* create_window_movie (void);
GtkWidget* create_guide (void);
GtkWidget* create_question (void);
GtkWidget* create_colorselectiondialog (void);
GtkWidget* create_unused (void);
GtkWidget* create_mag (void);
