/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window_main;
  GtkWidget *imageselection1;
  GtkWidget *image_win_1;
  GtkWidget *dialogwarning;
  GtkWidget *window_warped;
  GtkWidget *window_movie;
  GtkWidget *guide;
  GtkWidget *question;
  GtkWidget *colorselectiondialog;
  GtkWidget *unused;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (DATADIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window_main = create_window_main ();
  gtk_widget_show (window_main);
  imageselection1 = create_imageselection1 ();
  gtk_widget_show (imageselection1);
  image_win_1 = create_image_win_1 ();
  gtk_widget_show (image_win_1);
  dialogwarning = create_dialogwarning ();
  gtk_widget_show (dialogwarning);
  window_warped = create_window_warped ();
  gtk_widget_show (window_warped);
  window_movie = create_window_movie ();
  gtk_widget_show (window_movie);
  guide = create_guide ();
  gtk_widget_show (guide);
  question = create_question ();
  gtk_widget_show (question);
  colorselectiondialog = create_colorselectiondialog ();
  gtk_widget_show (colorselectiondialog);
  unused = create_unused ();
  gtk_widget_show (unused);

  gtk_main ();
  return 0;
}

