.\" Copyright (c) 1994-1997 Michael J. Gourlay
.TH XMORPH 1

.SH NAME
xmorph \- image warping and dissolving (morphing) for X window system

morph \- command line interface image morphing program

.SH SYNOPSIS
.B xmorph
.RB "[\|" \-start
.I srcimgfile
.RB "[\|" \-finish
.IR destimgfile "\|]\|]"
.RB "[\|" \-src
.I srcmeshfile
.RB "[\|" \-dst
.I dstmeshfile "\|]\|]"
.RB "[\|" \-help "\|]"

.B morph
.RB "[\|" \-start
.I srcimgfile
.RB "[\|" \-finish
.IR destimgfile "\|]\|]"
.RB "[\|" \-src
.I srcmeshfile
.RB "[\|" \-dst
.I dstmeshfile "\|]\|]"
.RB "[\|" \-out
.I outimgfile "\|]"
.RB "[\|" \-mt
.I morphtween "\|]"
.RB "[\|" \-dt
.I dissolvetween "\|]"
.RB "[\|" \-help "\|]"

.SH DESCRIPTION
.B xmorph
is a digital image warping and dissolving program, also known as a
"morphing" program.  It runs under the X Window System.  The primary
use of
.B xmorph
is to generate and modify meshes which control the shape of an image.
.B xmorph
also has the capacity to dissolve images together, and to generate a
sequence of warped and dissolved images.  When this sequence is made
into a movie, it is called a "morph".

.LP
.B morph
is a morphing program with no graphical user interface.
.B morph
performs image warping and dissolving but provides no means to create or
modify meshes.  The intent is to use
.B morph
after meshes have already been generated with
.B xmorph.
Since
.B morph
has no GUI, it can be run as a background job and can be distributed
over many machines or processes.  This parallelization of the task can
significanly speed up the image processing.
.B morph
can run on machines which have no display whatsoever, and is therefore
very portable.

.LP
Both
.B xmorph
and
.B morph
use a library called
.B libmorph
which can be used separately in the creation of other morphing
programs.

.LP
If
.I imgfile
names are provided on the command line, then those images are loaded
in.  Otherwise,
.B xmorph
generates images to be used in lieu of images
provided by the user.  Images may be loaded from menus within
.BR xmorph .
.LP
.B xmorph
has built-in help pages that answer questions about the details
of its use.  Run
.B xmorph
and look at the online help for more information.

.SH OPTIONS
.TP
.B \-start \fIsrcimgfile\fP
Read the
.I srcimgfile
as the "source" image.
.TP
.B \-finish \fIdestimgfile\fP
Read the
.I destimgfile
as the "destination" image.
.TP
.B \-src \fIsrcmeshfile\fP
Read the
.I srcmeshfile
as the "source" mesh.
.TP
.B \-dst \fIdestmeshfile\fP
Read the
.I destimgfile
as the "destination" mesh.
.TP
.B \-help
Display command line options.

.SH MORPH OPTIONS
.TP
.B \-out \fIoutimgfile\fP
Write the the output image to
.I outimgfile .
.TP
.B \-mt \fImorphtween\fP
Use
.I morphtween
as the warping tween parameter.  Values are from 0 to 1.
0 means that the shape of the output is according to the source mesh.
1 means that the shape is according to the destination mesh.  Default
value is 0.
.TP
.B \-dt \fIdissolvetween\fP
Use
.I dissolvetween
as the dissolve tween parameter.  Values are from 0 to 1.
0 means that the image of the output is according to the source image.
1 means that the image is according to the destination image.
Negative values indicate that a sigmoid sharpening function is to be
applied to make the dissolving more concentrated to values near 0.5.
The idea is that the
.I dissolvetween
value should be the negative of the
.I morphtween
value in order to have the dissolve be more rapid during middle values
of the warp tween parameter, and less rapid otherwise.  This makes the
morph more visually acceptable.  Default value is 0.

.SH "MAKING MOVIES"
.B xmorph
is NOT a tool for making movies.
.B xmorph
is intended to be used with OTHER tools for editting movies in the
digital domain.  I do not intend to add movie making abilities to
.BR xmorph .
.LP
Here is a brief explanation of how to make a movie from the images
generated by
.BR xmorph :
.LP
.B xmorph
uses the TrueVision Targa (TGA) image file format.  You can use
PBMplus, netpbm, ImageMagick or some other program to convert Targa to
other still image formats.  (This will be necessary if, for example,
you use the Berkeley MPEG encoder or want to make an animated GIF.)
See, e.g.,
ftp://ikaros.fysik4.kth.se/pub/netpbm/.
.LP
Use another program, such as Berkeley's mpeg_encode, or SGI's
dmconvert, or whirlgif to turn the sequence of images that
.B xmorph
created into a single animation.  See, e.g.,
ftp://mm-ftp.cs.berkeley.edu/pub/multimedia/mpeg/encode/.
.LP
Use another program, such as mpeg_play, xanim or movieplayer, to view
the animation.  See, e.g.,
ftp://mm-ftp.cs.berkeley.edu/pub/multimedia/mpeg/play/.
.LP
There are plenty of other programs available for viewing movies.

.SH AUTHOR
Written and Copyright (C) 1994-2000 by Michael J. Gourlay.
.LP
Help came from many places, including Andy Thaller, Warwick Allison,
and Mike Hoefelein.
.LP
The original morphing algorithm is presented in ``A Two-Pass Mesh
Warping Algorithm for Object Transformation and Image
Interpolation'', ILM Technical Memo #1030, Computer Graphics
Department, Lucasfilm Ltd., 1990.
.LP
Mesh-based digital image warping is discussed in detail in
.I Digital Image Warping
by George Wolberg.
.LP
Xmorph is a GNU program.

.SH "SEE ALSO"
.BR X (1),
.BR ppmtotga (1)
(part of netpbm or PBMplus),
.BR tgatoppm (1)
(part of netpbm or PBMplus),
.BR whirlgif (1),
.BR mpeg_encode (1)
from U.C. Berkeley,
.BR mpeg_play (1)
from U.C. Berkeley,
ImageMagick,
.BR dmconvert (1),
(under Silicon Graphics IRIX).
.BR movieplayer (1)
(under Silicon Graphics IRIX),
.BR xanim (1),
.BR GIMP (1).

.SH NOTES
The only image file type currently supported is Truevision Targa
(TGA) but
.B xmorph
will load any type of Targa, such as 8-bit, 15-bit, or 16-bit
colormapped or grayscale; 24-bit or 32-bit true color (with or
without alpha channel);  run-length encoded or uncompressed.
.LP
Some versions of the program "xv" can not read xmorph's TGA image files.
This is a bug in "xv", not in xmorph.
.LP
Use image conversion programs (such as those listed in the SEE ALSO
section) to convert to and from TGA image files for use with
.B xmorph and
.B morph .
.LP
Report bugs to gourlay@colorado-research.com or mennucc1@debian.org

.SH "WEB SITE"
http://sourceforge.net/projects/xmorph
.LP
http://colorado-research.com/~gourlay/
.LP
http://colorado-research.com/~gourlay/software/
.LP
http://colorado-research.com/~gourlay/software/Graphics/
.LP
http://colorado-research.com/~gourlay/software/Graphics/Xmorph/
