/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("gtkmorph");
gchar *s = N_("File menu");
gchar *s = N_("File");
gchar *s = N_("load session");
gchar *s = N_("save session");
gchar *s = N_("add an image");
gchar *s = N_("Quit");
gchar *s = N_("Edit");
gchar *s = N_("show all images");
gchar *s = N_("show mag");
gchar *s = N_("resulting image size...");
gchar *s = N_("show morph factors");
gchar *s = N_("Settings");
gchar *s = N_("Morph");
gchar *s = N_("the mesh of the resulting image is set to an interpolation of the input images' meshes, weighted by the ``mesh factors''");
gchar *s = N_("interpolate meshes");
gchar *s = N_("the input images are warped to the resulting mesh and blended using ``image blending factors'' as weights. It has the same effect as if you hit all the ``do warp'' buttons and then you hit the ``do blending'' button");
gchar *s = N_("morph images");
gchar *s = N_("adjust points of meshes confronting original images and the morph");
gchar *s = N_("adjust all meshes");
gchar *s = N_("equalize input images so that the subband of wavelet transform have the same energies");
gchar *s = N_("wavelet equalize");
gchar *s = N_("restore morph coefficients...");
gchar *s = N_("start");
gchar *s = N_("end");
gchar *s = N_("equal");
gchar *s = N_("stores internally the state of all mesh and image-blending factors (to make morph sequences)");
gchar *s = N_("store morph coefficients...");
gchar *s = N_("start");
gchar *s = N_("end");
gchar *s = N_("create and save many morphs, equally spaced between the morph start and the morph end (that you have already stored with the above menu)");
gchar *s = N_("morph sequence");
gchar *s = N_("Help");
gchar *s = N_("guide...");
gchar *s = N_("help...");
gchar *s = N_("generic help");
gchar *s = N_("warp help");
gchar *s = N_("morph help");
gchar *s = N_("why the beep?");
gchar *s = N_("load the image. This image may not be warped or morphed, but it may help in setting the resulting mesh");
gchar *s = N_("load\n"
              "image");
gchar *s = N_("load\n"
              "mesh");
gchar *s = N_("save\n"
              "mesh");
gchar *s = N_("``edit template'': view the loaded image and edit the mesh on it. \\n ``view morphed'': view the result of morphing.     ``v.morph&mesh'' as above but with the mesh.  ``edit eyes points'' sets the reference position of the eyes");
gchar *s = N_("edit template");
gchar *s = N_("view morph");
gchar *s = N_("v morph&meshes");
gchar *s = N_("edit eyes points");
gchar *s = N_("settings");
gchar *s = N_("set this mesh to be an interpolation of all other meshes, using ``mesh factors'' as weights");
gchar *s = N_("interpol.\n"
              "meshes");
gchar *s = N_("mix all the warped images in the ``resulting image'' using ``image blending factors'' as weights");
gchar *s = N_("do\n"
              "blending");
gchar *s = N_("the input images are warped to the resulting mesh and blended using ``image blending factors'' as weights.  It has the same effect as if you hit all the ``do warp'' buttons and then you hit the ``do blending'' button.");
gchar *s = N_("do\n"
              "morph");
gchar *s = N_("it saves whatever image is currently shown in the window");
gchar *s = N_("save\n"
              "image");
gchar *s = N_("back to guide");
gchar *s = N_("guide");
gchar *s = N_("add new feature to the end of list");
gchar *s = N_("new");
gchar *s = N_("rename");
gchar *s = N_("pack the selected points in this feature");
gchar *s = N_("pack");
gchar *s = N_("unpack this feature and transforms all points of it to selected points");
gchar *s = N_("unpack");
gchar *s = N_("delete last feature");
gchar *s = N_("delete");
gchar *s = N_("move single point");
gchar *s = N_("edit");
gchar *s = N_("move whole feature");
gchar *s = N_("move");
gchar *s = N_("stretch whole feature");
gchar *s = N_("stretch");
gchar *s = N_("-");
gchar *s = N_("select");
gchar *s = N_("unselect");
gchar *s = N_("assign point to feature");
gchar *s = N_("assign");
gchar *s = N_("error");
gchar *s = N_("resulting image size");
gchar *s = N_("width");
gchar *s = N_("height");
gchar *s = N_("x2");
gchar *s = N_("/2");
gchar *s = N_("apply");
gchar *s = N_("error!");
gchar *s = N_("load the selected image");
gchar *s = N_("OK");
gchar *s = N_("cancel");
gchar *s = N_("error!");
gchar *s = N_("load\n"
              "image");
gchar *s = N_("load\n"
              "mesh");
gchar *s = N_("save\n"
              "mesh");
gchar *s = N_("``edit mesh'': view the loaded image and edit the mesh on it.         ``view warp'': view the result of warping the loaded image from this mesh to the resulting mesh.               ``v. warp&meshes'' as before but with both meshes on.              ``choose subimage'' choose which subimage of the loaded image you wish to use.            You can also use the 'settings' button to change these settings more finely.");
gchar *s = N_("edit mesh");
gchar *s = N_("view warp");
gchar *s = N_("v. warp&meshes");
gchar *s = N_("choose subimage");
gchar *s = N_("settings");
gchar *s = N_("warp this image from this mesh to the resulting mesh, and show the result in this window or an accessory window");
gchar *s = N_("do\n"
              "warp");
gchar *s = N_("it saves whatever image is currently shown in the window");
gchar *s = N_("save\n"
              "image");
gchar *s = N_("back to guide");
gchar *s = N_("guide");
gchar *s = N_("error");
gchar *s = N_("these coefficents decide how much this image/mesh will influence the final morph");
gchar *s = N_("coefficients");
gchar *s = N_("image\n"
              "blending");
gchar *s = N_("mesh\n"
              "interp.");
gchar *s = N_("when you morph the images, or you ``do mixing'', this factor will measure how much this image will show in the mixing in the resulting image");
gchar *s = N_("when you use the ``interpolate meshes'' function, the ``mesh factor'' measures how much this mesh will influence the resulting image's mesh");
gchar *s = N_("subimage position");
gchar *s = N_("infer the subimage from the eyes position");
gchar *s = N_("reset");
gchar *s = N_("x coordinate of center");
gchar *s = N_("c x");
gchar *s = N_("y coordinate of center");
gchar *s = N_("c y");
gchar *s = N_("width");
gchar *s = N_("height");
gchar *s = N_("apply");
gchar *s = N_("warning");
gchar *s = N_("ok");
gchar *s = N_("warning!");
gchar *s = N_("warped image");
gchar *s = N_("unselect point");
gchar *s = N_("select point");
gchar *s = N_("assign point");
gchar *s = N_("adjust");
gchar *s = N_("add horizontal line");
gchar *s = N_("add vertical line");
gchar *s = N_("del horizontal line");
gchar *s = N_("del vertical line");
gchar *s = N_("smooth");
gchar *s = N_("gtkmorph movie");
gchar *s = N_("how many frames will be saved; each will be saved in a file");
gchar *s = N_("how many frames");
gchar *s = N_("the files of the frames will be numbered sequentially starting from this number");
gchar *s = N_("number of first file");
gchar *s = N_("file base name");
gchar *s = N_("frame");
gchar *s = N_("animations");
gchar *s = N_("creates an animated gif (needs 'convert' from imagemagick) and plays it (needs 'animate' from imagemagick)");
gchar *s = N_("create animated gif");
gchar *s = N_("show animated sequence after saving it all  (needs 'animate' command from imagemagick)");
gchar *s = N_("animate sequence");
gchar *s = N_("resaves and replays animations");
gchar *s = N_("replay");
gchar *s = N_("creates an mpeg file and plays it; will use a parameter file (see help) (needs 'mpeg_encode' and 'mpeg_play')");
gchar *s = N_("creates mpeg");
gchar *s = N_("creates and saves all morphs, builds animations");
gchar *s = N_(" ok ");
gchar *s = N_("cancel");
gchar *s = N_("help");
gchar *s = N_("gtkmorph guide");
gchar *s = N_("go back to previous guide pane");
gchar *s = N_("prev");
gchar *s = N_("do what is proposed in this pane");
gchar *s = N_("do it");
gchar *s = N_("skip this and go to next guide pane");
gchar *s = N_("next");
gchar *s = N_("question");
gchar *s = N_("Yes");
gchar *s = N_("No");
gchar *s = N_("question?");
gchar *s = N_("Select Color");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Help");
gchar *s = N_("window1");
gchar *s = N_("move single point");
gchar *s = N_("edit");
gchar *s = N_("move whole feature");
gchar *s = N_("move");
gchar *s = N_("stretch whole feature");
gchar *s = N_("stretch");
gchar *s = N_("gtkmorph mag");
gchar *s = N_("1");
gchar *s = N_("track");
